FROM ubuntu:17.10

# We need ca-certificates since we need to pull files using https
# Make is installed for interactive test runs
RUN apt-get update && apt-get install \
	python3 \
	python3-apt \
	ca-certificates \
	make \
	-y

COPY . /root/.dotfiles

WORKDIR /root/.dotfiles
