FROM ubuntu:16.04

# We need ca-certificates since we need to pull files using https
RUN apt-get update && apt-get install \
	python3 \
	python3-apt \
	ca-certificates \
	-y

COPY . /root/.dotfiles

WORKDIR /root/.dotfiles
