---
# Usage
# $ ansible-playbook server_ansible.yml
# -i <inventory>
# --vault-password ~/.vault_password
# -e ansible_become=false
# -e ansible_ssh_user=dani
# --ssh-common-args='-o ProxyJump=jumphost'
# -l <instance>
- hosts: all
  strategy: free
  tasks:
    - name: Create dirs
      tags: [rc-files, minimal]
      file:
        path: '{{ item }}'
        state: directory
        mode: 0770
        recurse: true
      with_items:
        - '{{ ansible_env.HOME }}/.dotfiles'
        - '{{ ansible_env.HOME }}/.config/nvim'

    - name: Copy shell files
      tags: [rc-files, minimal]
      copy:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'

      with_items:
        - src: '{{ playbook_dir }}/zshrc'
          dest: '{{ ansible_env.HOME }}/.zshrc'
        - src: '{{ playbook_dir }}/fzf-helpers.zsh'
          dest: '{{ ansible_env.HOME }}/.dotfiles/fzf-helpers.zsh'
        - src: '{{ playbook_dir }}/git.zsh'
          dest: '{{ ansible_env.HOME }}/.dotfiles/git.zsh'

    - name: Set zsh as the default shell
      become: true
      user:
        name: '{{ ansible_user_id }}'
        shell: /bin/zsh
    - tags: [dependencies, minimal]
      name: Install apt dependencies
      become: true
      failed_when: false # Fail and skip on older distros
      apt:
        name: [zsh, ripgrep, net-tools, htop, xclip, httpie, ncdu, direnv]
        update_cache: true

    - import_role: name=fetch
      tags: always

    - import_role: name=fd
      tags: fd

    - import_role: name=fzf
      tags: fzf

    - import_role: name=bat
      tags: bat

    - import_role: name=duf
      tags: duf

    - import_role: name=dust
      tags: duf

    - import_role: name=neovim
      vars:
        server: true
      tags: neovim

    - import_role: name=navi
      tags: navi
