---
- name: Fetch binary
  shell: >-
    fetch --repo
    https://github.com/denisidoro/navi
    --release-asset=".*x86_64-unknown-linux-musl.*"
    --tag=v{{ navi_tag }} /tmp

- name: Extract the binary
  vars:
    ansible_become: true
  unarchive:
    src: '/tmp/navi-v{{ navi_tag }}-x86_64-unknown-linux-musl.tar.gz'
    dest: /usr/local/bin/
    remote_src: true

- name: Clone my cheats
  git:
    repo: https://github.com/danihodovic/cheats.git
    dest: ~/repos/cheats

- name: Create parent dir
  file:
    state: directory
    dest: ~/.local/share/navi/cheats/
    recurse: true

- name: Symlink cheats
  file:
    state: link
    src: ~/repos/cheats
    dest: ~/.local/share/navi/cheats/danihodovic__cheats
    force: true
