---
- name: Fetch the Delta deb pkg
  shell: >-
    fetch --repo https://github.com/dandavison/delta
    --github-oauth-token={{ lookup("env", "GITHUB_TOKEN") }}
    --release-asset='git-delta_.*amd64.deb'
    --tag={{ delta_version }}
    /tmp/

- name: Install deb
  become: true
  apt:
    deb: /tmp/git-delta_{{ delta_version }}_amd64.deb

- name: Git-lfs install script
  become: true
  shell: >-
    curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash

- name: Install git-lfs
  become: true
  apt:
    name: git-lfs
