#!/usr/bin/env bash
if [[ "$#" -ne 2 ]]; then
  echo Usage: $(basename $0) workspace_id_1 workspace_id_2
  exit 1
fi

i3-msg "rename workspace $1 to temporary; rename workspace $2 to $1; rename workspace temporary to $2"
