#!/usr/bin/env zsh
# TODO: Kill all open windows too, optionally.
size=$1
if [ -n "$size" ]; then
  sed "s/Xft.dpi: *[[:digit:]]\+/Xft.dpi: $size/" .Xresources -i
  xrdb ~/.Xresources
  i3-msg restart
else
  echo Provide size as the first argument
fi
