---
- name: Fetch the repo
  shell: >-
    fetch --repo
    https://github.com/sharkdp/fd
    --github-oauth-token={{ lookup("env", "GITHUB_TOKEN") }}
    --release-asset="fd_.*_amd64.deb"
    --tag=v{{ fd_tag }} /tmp/

- name: Install deb package
  vars:
    ansible_become: true
  apt:
    deb: '/tmp/fd_{{ fd_tag }}_amd64.deb'
