---
- name: Install xsel for yank
  become: true
  apt:
    name: xsel

- name: Create directories
  file:
    state: directory
    path: '{{ item }}'
  loop:
    - '{{ neovim_dest | dirname }}'
    - '{{ ansible_env.HOME}}/.config/nvim'
    - '{{ vim_plug_path | dirname }}'

- name: Fetch the binary
  shell: >-
    fetch
    --github-oauth-token={{ lookup("env", "GITHUB_TOKEN") }}
    --repo https://github.com/neovim/neovim
    --release-asset='nvim.appimage'
    --tag {{ neovim_version }} /tmp/

- name: Move appimage to path
  become: true
  ansible.builtin.copy:
    src: /tmp/nvim.appimage
    dest: /usr/local/bin/nvim
    mode: '0755'

- name: Symlink config files
  include: ./copy_config.yml
  loop:
    - src: '{{ role_path }}/files/vimrc'
      dest: '{{ ansible_env.HOME}}/.config/nvim/init.vim'
    - src: '{{ role_path }}/files/coc-settings.json'
      dest: '{{ ansible_env.HOME}}/.config/nvim/coc-settings.json'

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: '{{ vim_plug_path }}'
